builds:
  - goos:
      - darwin
    goarch:
      - amd64
    ldflags:
      - -X main.version={{ .Version }}
      - -X main.revision={{ .ShortCommit }}

release:
  github:
    owner: kitagry
    name: bqls
  extra_files:
    - glob: "build/*.zip"
